name: cfpylearning
dependencies:
- libgfortran=1.0=0
- openblas=0.2.14=1
- system=5.8=2
- flask=0.10.1=py27_1
- itsdangerous=0.24=py27_0
- jinja2=2.7.3=py27_1
- markdown=2.6.2=py27_0
- markupsafe=0.23=py27_0
- nose=1.3.7=py27_0
- numpy=1.9.2=py27_0
- openssl=1.0.1k=1
- pip=7.0.3=py27_0
- python=2.7.10=0
- readline=6.2=2
- scikit-learn=0.16.1=np19py27_0
- scipy=0.15.1=np19py27_0
- setuptools=17.1.1=py27_0
- sqlite=3.8.4.1=1
- tk=8.5.18=0
- werkzeug=0.10.4=py27_0
- zlib=1.2.8=0
- pip:
  - redis==2.10.3
